### ISSUE TITLE
Only the C:\ drive is scanned in the Log4J script

### ISSUE THREAD

**Issue by yllekz** [N-able/ScriptsAndAutomationPolicies#33]
In regards to this:

https://github.com/N-able/ScriptsAndAutomationPolicies/blob/master/Vulnerability%20-%20CVE-2021-44228%20(Log4j)/get-log4jrcevulnerability.ps1

Is there a reason only the C:\ drive is included in the Get-ChildItem calls? Ideally one should check for all drive letters and scan them all. Servers and endpoints will often have data or application drives.

**Comment by prejay** [comment]
Now fixed in 0.1.9+
